### ISSUE TITLE
Symbol list

### ISSUE THREAD

**Issue by bibinvargheset** [jugaad-py/jugaad-data#10]
If there was a function to list all possible Stocks (symbols) and Fno entities it will be good.

**Comment by yash12392** [comment]
You can rather call this [API]( https://api.kite.trade/instruments) to get the instrument list daily, it gets updated every day by Zerodha and does not require a subscription.

**Comment by sevakram** [comment]
@bibinvargheset for exhaustive list, you can get it in bhavcopy as well.
Similarly for F&O list you can download F&O bhavcopy and filter on FUTSTK or OPTSTK

Additionally i remember seeing it somewhere in live api as well, but i will have to check. There is a lot of data given in live API but it gets difficult to document everything.
