### ISSUE TITLE
Historical data is not consistent for few tickers. 

### ISSUE THREAD

**Issue by Matt-john** [jugaad-py/jugaad-data#17]
Hello Team, 

This below code fetches data for ABBOTINDIA till 29th June 2021
df = stock_df(symbol = 'ABBOTINDIA', from_date=date(2021, 5, 1), to_date=date.today(),series="EQ")
But the same code fetches data till 28th June for 3MINDIA
df = stock_df(symbol = 'ABBOTINDIA', from_date=date(2021, 5, 1), to_date=date.today(),series="EQ")

While trying to extract data for ADANIGREEN, it gives OHLC data till June 08th, 2021

**Comment by ChillarAnand** [comment]
i tried to download NIFTY FIFTY index historical data.for this symbol also we are facing the same issue.

**Comment by sevakram** [comment]
Can you please check the data on new website as well? We need to isolate the issue, is it with NSE or in the library

**Comment by sevakram** [comment]
I am not able to replicate the issue, @ChillarAnand , @Matt-john , request you to share the full code.

It is working as expected for me.
