### ISSUE TITLE
Vix returns nothing on n.live_index('INDIA VIX')

### ISSUE THREAD

**Issue by AdityaPunetha** [jugaad-py/jugaad-data#20]
print(n.live_index('INDIA VIX')) returns {} even though 'INDIA VIX' shows up when using print(n.all_indices())
also how do i get data regarding usdinr fut ?

**Comment by sevakram** [comment]
NSE does not provide live data on VIX, Please check below link, there is live webpage for each index except VIX

https://www.nseindia.com/market-data/live-market-indices

If you are interested in live value of INDIA VIX, you can still get it from `all_indices` method as below-

```python
d = n.all_indices()
x = list(filter(lambda x: x['index']=='INDIA VIX', d['data']))
print(x[0]['index'], x[0]['last'])
```

Output:
```
INDIA VIX 16.2225
```
