### ISSUE TITLE
'index_option_chain' function returns empty data set

### ISSUE THREAD

**Issue by ronaldpaul** [jugaad-py/jugaad-data#23]
`NSELive().index_option_chain("NIFTY")` returns empty result set {}. Suddenly it stopped working and returns empty result set and doesn't return expiry date.

**Comment by sevakram** [comment]
Hi @ronaldpaul ,

Can you please share the sample code and more observation. I suspect two reasons-
1. NSE giving blank response
2. Caching mechanism not working properly

Your code block will help me eliminate reasons.

**Comment by ronaldpaul** [comment]
Hi @sevakram , It looks like NSE India website API issue. It returns empty resultset in the URL in which you are hitting. In the past few weeks, it has been a big issue. Could you fetch the expiry dates from any other reliance source API please?

Thanks
