### ISSUE TITLE
error  (demo_crushed) not found

### ISSUE THREAD

**Issue by mangeshsable1975** [jugaad-py/jugaad-data#25]
![error](https://user-images.githubusercontent.com/67979855/143690671-0d5927e9-9ac6-4bbf-a70c-cd87bcac220d.png)

**Comment by sevakram** [comment]
Hi @mangeshsable1975 ,

I am not sure why VSCode is not able to find `demo_crashed`, its already defined on line number 83.

Also all tests are running fine as well, which would not be possible without a defined function.

**Comment by mangeshsable1975** [comment]
Hi sevakram
I am finding same problem with other repository also does v.s
 Code have some issues
