### ISSUE TITLE
Error in fetching expiry dates

### ISSUE THREAD

**Issue by ronaldpaul** [jugaad-py/jugaad-data#27]
Hi, The library was working properly till day before yesterday and fetching the expiry dates as mentioned in the documentation. However, now it is through the error message and not fetching the expiry dates. Following is the code that I was using to fetch the current expiry date. It looks like in the results returned, there is no any key with the name 'records'. Only 'filtered' key with some values is being returned. Is it any API change in the NSE source or problem with Jugaad library? Please help.

`n = NSELive()`
`option_chain = n.index_option_chain("BANKNIFTY")`
`expiry = option_chain['records']['expiryDates'][00]`

**Comment by sevakram** [comment]
This seems to work now. It most probably is malfunction at NSE's end. `jugged-data` is just a messenger.

if you look at the internals. It simply is fetching the request.

```python
def index_option_chain(self, symbol="NIFTY"):
        data = {"symbol": symbol}
        return self.get("index_option_chain", data)
```
