### ISSUE TITLE
Is NSE Blocking IP addresses?

### ISSUE THREAD

**Issue by Newbie2Pro** [jugaad-py/jugaad-data#28]
It appears that NSE may be blocking IP addresses. After a few hundred historical downloads, we get the below error for all dates:

**Failed to download for below dates, these might be holidays, please check -
2015-01-01
2015-01-02
2015-01-05
2015-01-06
2015-01-07
2015-01-08
2015-01-09
2015-01-12
2015-01-13
2015-01-14
2015-01-15
2015-01-16
2015-01-19**

**Comment by sevakram** [comment]
Hi @Newbie2Pro 

Please share the code snippets and error message. The issue description has no information about which function, what parameters etc.
