### ISSUE TITLE
Http2 Support (HTTPX)

### ISSUE THREAD

**Issue by shoebshah64** [jugaad-py/jugaad-data#44]
### Describe the required feature

jugad-data is using requests library does not support http2 but now nse support http2 protocol which faster and more efficient.
Kindly use httpx library instead of requests.

### URL where you observed this data

https://www.python-httpx.org/http2/

**Comment by sevakram** [comment]
That is an interesting suggestion, whether we switch to httpx+http2 or not depends on 
1. How much code change is involved (Efforts in adding new features vs efforts in increasing performance)
2. How much faster it is, even right now, we use thread pool to fetch data in parallel. Requests library does use connection pooling so we are not going to open connection on every request. So unless there is a 2x or more performance gain... Usually its not worth the effort

So when I get time, I will probably use it in below priority 
1. Fix existing bugs
2. Add new features
3. Improve performance
