### ISSUE TITLE
Rate limiting 

### ISSUE THREAD

**Issue by rexdivakar** [jugaad-py/jugaad-data#59]
Do we have any rate limiting if so can you please share the details of it ? Cox i have a requirement to dump a batch data of all 1924 stocks at once every day. Kindly advice

**Comment by sevakram** [comment]
Hi @rexdivakar 
Jugaad-trader doesn't put any limits, it is NSE that may put limit and I can see that request fail if we download too much, but I don't know what that limit is.

Also, if you are downloading bhavcopy once every day, that is reasonable traffic, and relatively less data and this should be fi
