### ISSUE TITLE
Can we get Tik by Tik Data?

### ISSUE THREAD

**Issue by subodhcjoshi82** [jugaad-py/jugaad-data#6]
Hi 

Can you please tell me if we can get the tik by tik data.

**Comment by sevakram** [comment]
Hi @subodhcjoshi82 

`jugaad-data` does not support tick data and not sure if it'll be part of the library or not.

But I've written a jugaad script to download tick data from NSE's website. Hope it helps

[https://marketsetup.in/posts/tick-data/](https://marketsetup.in/posts/tick-data/)

**Comment by subodhcjoshi82** [comment]
Can we Connect ..Want to Discuss something with you?

**Comment by sevakram** [comment]
You can reach-out to me on mail - contact@marketsetup.in
or on telegram - jugaader
