### ISSUE TITLE
Using Proxies to download Data

### ISSUE THREAD

**Issue by yash12392** [jugaad-py/jugaad-data#7]
Hi, you might consider adding in a proxy variable when instantiating the NSELive or NSEHistory class to download data, the reason being if an individual is making a lot of requests to the NSE website for historical data or live prices - proxies come in handy so that the user does not get blocked. 
I had my own version of the code to download all the data but your library is no doubt much more better.

Let me know if you are looking for more feedback!

https://2.python-requests.org/en/latest/user/advanced/#proxies

**Comment by sevakram** [comment]
Thanks for the suggestion and appreciation!  

I was planning to cache the result for 10-15 seconds so that there's some self rate limiting mechanism.

I did not quite understand the proxy part, in terms of mechanism, how it'll prevent blocking.

**Comment by sevakram** [comment]
Also, NSEHistory caches the data on local disk, so if you are say requesting data for last 1 year every day, it'll only download the current month data which is getting refreshed and take rest of the data from local disk cache. So there will be only small number of requests that go to NSE.

**Comment by yash12392** [comment]
Hi, thanks for getting back and sorry for the delay, after going through your code again, your comments make sense and looks good!
