### ISSUE TITLE
Refreshing and getting live data

### ISSUE THREAD

**Issue by mnips** [jugaad-py/jugaad-data#8]
How often can the live data be fetched (like minute intervals). Also, could you please elaborate how to fetch that at a minute basis through code for say options.

**Comment by sevakram** [comment]
Hi
I did not get a time to run it when market was live, but you can try this-

`test_script.py`

```python
from jugaad_data import nse
from datetime import datetime
import time
DELAY = 60

n = nse.NSELive()

print("LastPriceTime\tLocalTime\tCE\tStrike\tPE")
while True:
    option_chain = n.index_option_chain("NIFTY")
    for option in option_chain['filtered']['data']:
        print("{}\t{}\t{}\t{}\t{}".format(option_chain['records']['timestamp'], datetime.now(), option['CE']['lastPrice'], option['strikePrice'], option['PE']['lastPrice']))
    time.sleep(DELAY)
```

run it as below when market is running

```python test_script.py > liveprice.txt ```

* Observe the columns `LastPriceTime` and `LocalTime`. This will give you an idea about to what extent the quotes are delayed.
* Reduce DELAY value and observe how low can you go. Basically if you ping within very short time, you might get the same price and timestamp if the update time is slow.

**Comment by sevakram** [comment]
Closing as its not a library related issue.
